sudo: false
language: java

# skip default "install" command
install: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    - GRADLE_ARGS="-Djava.awt.headless=true"
    # Building source and binary distributions takes time, and it does not verify much, so we skip it in CI
    - SKIP_DIST_TASKS="$GRADLE_ARGS -PskipDist"

matrix:
  include:
    - name: Tests with OpenJDK 8 + code coverage
      jdk: openjdk8
      script:
        - ./gradlew $GRADLE_ARGS check createDist jacocoReport
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - name: Tests with OpenJDK 11
      jdk: openjdk11
      script:
        - ./gradlew $SKIP_DIST_TASKS -PskipCheckstyle build createDist
    - name: Tests with OpenJDK EA
      jdk: openjdk-ea
      script:
        - ./gradlew $SKIP_DIST_TASKS -PskipCheckstyle build createDist
  allow_failures:
    - jdk: openjdk-ea
