language: java
install: ant download_jars install; cat /etc/hosts
before_script: echo "127.0.0.1 "`hostname` | sudo tee /etc/hosts
script: ant -Djava.awt.headless=true test
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
addons:
  hostname: short-hostname
